[workspace]
resolver = "3"
members = ["library/cyclone-rs","robot-core"]

[workspace.dependencies]
jzlog = { path = "library/jzlog" }
jzbtree = { path = "library/jzbtree" }

# 外部依赖
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = "1.0"
nix = "0.30"
libloading = "0.8"
