name: ROS2 Jazzy CI

on:
  push:
    branches: []
  pull_request:
    branches: []

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-x64:
    runs-on: ubuntu-24.04
    container:
      image: rwthika/ros2:jazzy-ros-base-amd64
    steps:
      - uses: actions/checkout@v5

      # 安装 Rust nightly
      - name: Set up Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
          targets: x86_64-unknown-linux-gnu

      # 构建
      - name: Build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          sudo bash tools/lib_update.sh
          bash tools/build.sh

  build-and-test-arm64:
    runs-on: ubuntu-24.04-arm
    container:
      image: rwthika/ros2:jazzy-ros-base-arm64
    steps:
      - uses: actions/checkout@v5

      # 安装 Rust nightly
      - name: Set up Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
          targets: aarch64-unknown-linux-gnu

      # 构建
      - name: Build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          sudo bash tools/lib_update.sh
          bash tools/build.sh
